apiVersion: v1
kind: Namespace
metadata:
  name: demo2-git
  labels:
    k8smgmt.io/project: madhuproject
    CostCenter: a
    owner: b
    env: dev
    priority: high
    sevirity: low
  annotations:
    akey1: avalue1
    akey2: avalue2
